build:
  maxIssues: 0

complexity:
  TooManyFunctions:
    active: false
  LongParameterList:
    active: true
    functionThreshold: 8

style:
  WildcardImport:
    active: false

naming:
  PackageNaming:
    active: false
