name: Android CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'LICENSE'
    - 'NOTICE'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: download dependencies
      run: ./core/scripts/get-deps.sh
    - name: Build with Gradle
      run: ./gradlew build
