name: Build

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore:
      - '.npmignore'
      - '.idea/**'
      - '.vscode/**'
      - 'LICENSE'
      - '*.md'
      - 'bumpver.toml'
      - 'commitlint.config.cjs'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
  pull_request:
    paths-ignore:
      - '.npmignore'
      - '.idea/**'
      - '.vscode/**'
      - 'LICENSE'
      - '*.md'
      - 'bumpver.toml'
      - 'commitlint.config.cjs'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip build]') == false

    strategy:
      matrix:
        java-version: [21]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
        with:
          dependency-graph: generate-and-submit

      - name: download dependencies
        run: ./core/scripts/get-deps.sh

      - name: Build with Gradle
        run: ./gradlew build
